"""
staticschedule — Sabit haftalık/günlük yayın akışı döngüsü.

Her hafta/gün aynı programı tekrar eden kanallar için kullanılır.

Format iki türlü olabilir:
  - Haftalık (farklı günler): "tr.kanal": {"tz": TZ, "days": {0: [...], 1: [...], ...}}
  - Günlük (her gün aynı): "tr.kanal": {"tz": TZ, "daily": [...]}

Tuple: (saat, dakika, başlık) veya (saat, dakika, başlık, açıklama)

source_id = channel_id (channels.yaml'da kanalın tvg-id'si ile eşleşir)
"""
from __future__ import annotations
from datetime import datetime, timedelta
from typing import List, Dict, Tuple

from dateutil import tz

from adapters.base import BaseAdapter
from models import Programme
from normalize import ist

DE_TZ = tz.gettz("Europe/Berlin")    # Almanya saati (yaz/kış otomatik)
IST_TZ = tz.gettz("Europe/Istanbul")

# Gün numarası: 0=Pazartesi, 1=Salı, ..., 6=Pazar
SCHEDULES: Dict[str, Dict] = {

    # ── KANAL 6 — Haftalık yayın akışı ───────────────────────────
    "tr.kanal6": {
        "tz": IST_TZ,
        "days": {
            0: [  # Pazartesi
                ( 7, 0, "Güneş Doğarken"), ( 8,30, "Çizgi Film"),
                ( 9, 0, "Mutlu Yaşam İçin"), (10, 0, "Bir Başka Sabah"),
                (12, 0, "Öğle Haberi"), (12,30, "Burada Engelsizsin"),
                (13,30, "İş'te Moda"), (14,30, "İzleyicinin Seyir Defteri"),
                (15,30, "Dikkat Sağlık"), (17, 0, "İş'te Kariyer"),
                (18, 0, "SIT-COM Captain"), (19, 0, "Ana Haber"),
                (20, 0, "Kimde Kaldı?"), (21,30, "Faktör"),
                (23, 0, "Gece Sineması"), ( 1, 0, "Bi' Başka Ara"),
                ( 1,30, "Son Çıkış"), ( 3, 0, "Konser"),
                ( 5, 0, "Belgesel"), ( 6, 0, "Müzik"),
            ],
            1: [  # Salı
                ( 7, 0, "Güneş Doğarken"), ( 8,30, "Çizgi Film"),
                ( 9, 0, "Mutlu Yaşam İçin"), (10, 0, "Bir Başka Sabah"),
                (12, 0, "Öğle Haberi"), (12,30, "Burada Engelsizsin"),
                (13,30, "Notalara Yolculuk"), (14,30, "1 Kadın 4 Konuk"),
                (15,30, "Dikkat Sağlık"), (17, 0, "İş'te Kariyer"),
                (18, 0, "SIT-COM Captain"), (19, 0, "Ana Haber"),
                (20, 0, "Kimde Kaldı?"), (21,30, "Önce İletişim"),
                (23, 0, "Gece Sineması"), ( 1, 0, "Bi' Başka Ara"),
                ( 1,30, "Son Çıkış"), ( 3, 0, "Konser"),
                ( 5, 0, "Belgesel"), ( 6, 0, "Müzik"),
            ],
            2: [  # Çarşamba
                ( 7, 0, "Güneş Doğarken"), ( 8,30, "Çizgi Film"),
                ( 9, 0, "Mutlu Yaşam İçin"), (10, 0, "Bir Başka Sabah"),
                (12, 0, "Öğle Haberi"), (12,30, "Burada Engelsizsin"),
                (13,30, "İş'te Moda"), (14,30, "1 Kadın 4 Konuk"),
                (15,30, "Dikkat Sağlık"), (17, 0, "X'in Dükkânı"),
                (18, 0, "SIT-COM Captain"), (19, 0, "Ana Haber"),
                (20, 0, "Kimde Kaldı?"), (21,30, "Tebdil-i Mekan"),
                (23, 0, "Gece Sineması"), ( 1, 0, "Bi' Başka Ara"),
                ( 1,30, "Son Çıkış"), ( 3, 0, "Konser"),
                ( 5, 0, "Belgesel"), ( 6, 0, "Müzik"),
            ],
            3: [  # Perşembe
                ( 7, 0, "Güneş Doğarken"), ( 8,30, "Çizgi Film"),
                ( 9, 0, "Mutlu Yaşam İçin"), (10, 0, "Bir Başka Sabah"),
                (12, 0, "Öğle Haberi"), (12,30, "Burada Engelsizsin"),
                (13,30, "Notalara Yolculuk"), (14,30, "1 Kadın 4 Konuk"),
                (15,30, "Dikkat Sağlık"), (17, 0, "X'in Dükkânı"),
                (18, 0, "SIT-COM Captain"), (19, 0, "Ana Haber"),
                (20, 0, "Kimde Kaldı?"), (21,30, "Avrupa Durağı"),
                (23, 0, "Gece Sineması"), ( 1, 0, "Bi' Başka Ara"),
                ( 1,30, "Son Çıkış"), ( 3, 0, "Konser"),
                ( 5, 0, "Belgesel"), ( 6, 0, "Müzik"),
            ],
            4: [  # Cuma
                ( 7, 0, "Güneş Doğarken"), ( 8,30, "Çizgi Film"),
                ( 9, 0, "Mutlu Yaşam İçin"), (10, 0, "Bir Başka Sabah"),
                (12, 0, "Öğle Haberi"), (12,30, "Burada Engelsizsin"),
                (13,30, "İş'te Moda"), (14,30, "İzleyicinin Seyir Defteri"),
                (15,30, "Dikkat Sağlık"), (17, 0, "X'in Dükkânı"),
                (18, 0, "Dizi Pati and Pati"), (19, 0, "Ana Haber"),
                (20, 0, "Kimde Kaldı?"), (21,30, "Asansör"),
                (23, 0, "Gece Sineması"), ( 1, 0, "Bi' Başka Ara"),
                ( 1,30, "Son Çıkış"), ( 3, 0, "Konser"),
                ( 5, 0, "Belgesel"), ( 6, 0, "Müzik"),
            ],
            5: [  # Cumartesi
                ( 7, 0, "Ana Sayfa"), ( 8,30, "Çizgi Film"),
                ( 9, 0, "12'den Vuranlar"), (10, 0, "Pembe Yaşamlar"),
                (12, 0, "Öğle Haberi"), (12,30, "Turizm 'E'"),
                (13,30, "Star Pabuç"), (14,30, "Engelsiz Mekanlar"),
                (15,30, "Ekonomik Yaşam"), (17, 0, "Bi' Başka Ara"),
                (18, 0, "Hayatımızı Değiştirenler"),
                (19, 0, "X ile Hafta Sonu Haberleri"),
                (20, 0, "Tüm Engellere Rağmen Ben De Yapabilirim"),
                (23, 0, "Gece Sineması"), ( 1, 0, "Bi' Başka Ara"),
                ( 1,30, "Son Çıkış"), ( 3, 0, "Konser"),
                ( 5, 0, "Belgesel"), ( 6, 0, "Müzik"),
            ],
            6: [  # Pazar
                ( 7, 0, "Belgesel"), ( 8,30, "Çizgi Film"),
                ( 9, 0, "12'den Vuranlar"), (10, 0, "Pembe Yaşamlar"),
                (12, 0, "Öğle Haberi"), (12,30, "Turizm 'E'"),
                (13,30, "Star Pabuç"), (14,30, "Engelsiz Mekanlar"),
                (15,30, "Ekonomik Yaşam"), (17, 0, "Bi' Başka Ara"),
                (18, 0, "Hayatımızı Değiştirenler"),
                (19, 0, "X ile Hafta Sonu Haberleri"),
                (20, 0, "Tüm Engellere Rağmen Ben De Yapabilirim"),
                (23, 0, "Gece Sineması"), ( 1, 0, "Bi' Başka Ara"),
                ( 1,30, "Son Çıkış"), ( 3, 0, "Konser"),
                ( 5, 0, "Belgesel"), ( 6, 0, "Müzik"),
            ],
        },
    },


    # ── POWER DANCE — 2 saatlik elektronik/dans döngüsü ──────────
    "tr.powerdance": {
        "tz": IST_TZ,
        "daily": [
            ( 0, 0, "Müzik Yayını", "Dance, elektronik ve EDM müzik yayını"),
            ( 2, 0, "Müzik Yayını", "Dance, elektronik ve EDM müzik yayını"),
            ( 4, 0, "Müzik Yayını", "Dance, elektronik ve EDM müzik yayını"),
            ( 6, 0, "Müzik Yayını", "Dance, elektronik ve EDM müzik yayını"),
            ( 8, 0, "Müzik Yayını", "Dance, elektronik ve EDM müzik yayını"),
            (10, 0, "Müzik Yayını", "Dance, elektronik ve EDM müzik yayını"),
            (12, 0, "Müzik Yayını", "Dance, elektronik ve EDM müzik yayını"),
            (14, 0, "Müzik Yayını", "Dance, elektronik ve EDM müzik yayını"),
            (16, 0, "Müzik Yayını", "Dance, elektronik ve EDM müzik yayını"),
            (18, 0, "Müzik Yayını", "Dance, elektronik ve EDM müzik yayını"),
            (20, 0, "Müzik Yayını", "Dance, elektronik ve EDM müzik yayını"),
            (22, 0, "Müzik Yayını", "Dance, elektronik ve EDM müzik yayını"),
        ],
    },
    # ── POWER LOVE — 2 saatlik romantik müzik döngüsü ────────────
    "tr.powerlove": {
        "tz": IST_TZ,
        "daily": [
            ( 0, 0, "Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik yayını"),
            ( 2, 0, "Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik yayını"),
            ( 4, 0, "Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik yayını"),
            ( 6, 0, "Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik yayını"),
            ( 8, 0, "Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik yayını"),
            (10, 0, "Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik yayını"),
            (12, 0, "Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik yayını"),
            (14, 0, "Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik yayını"),
            (16, 0, "Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik yayını"),
            (18, 0, "Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik yayını"),
            (20, 0, "Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik yayını"),
            (22, 0, "Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik yayını"),
        ],
    },
    # ── POWERTURK SLOW — 2 saatlik yavaş tempo döngüsü ──────────
    "tr.powerturkslow": {
        "tz": IST_TZ,
        "daily": [
            ( 0, 0, "Müzik Yayını", "Yavaş tempo, duygusal Türkçe müzik yayını"),
            ( 2, 0, "Müzik Yayını", "Yavaş tempo, duygusal Türkçe müzik yayını"),
            ( 4, 0, "Müzik Yayını", "Yavaş tempo, duygusal Türkçe müzik yayını"),
            ( 6, 0, "Müzik Yayını", "Yavaş tempo, duygusal Türkçe müzik yayını"),
            ( 8, 0, "Müzik Yayını", "Yavaş tempo, duygusal Türkçe müzik yayını"),
            (10, 0, "Müzik Yayını", "Yavaş tempo, duygusal Türkçe müzik yayını"),
            (12, 0, "Müzik Yayını", "Yavaş tempo, duygusal Türkçe müzik yayını"),
            (14, 0, "Müzik Yayını", "Yavaş tempo, duygusal Türkçe müzik yayını"),
            (16, 0, "Müzik Yayını", "Yavaş tempo, duygusal Türkçe müzik yayını"),
            (18, 0, "Müzik Yayını", "Yavaş tempo, duygusal Türkçe müzik yayını"),
            (20, 0, "Müzik Yayını", "Yavaş tempo, duygusal Türkçe müzik yayını"),
            (22, 0, "Müzik Yayını", "Yavaş tempo, duygusal Türkçe müzik yayını"),
        ],
    },
    # ── POWERTURK AKUSTİK — 2 saatlik akustik döngüsü ───────────
    "tr.powerturkakustik": {
        "tz": IST_TZ,
        "daily": [
            ( 0, 0, "Müzik Yayını", "Akustik Türkçe müzik ve unplugged performanslar"),
            ( 2, 0, "Müzik Yayını", "Akustik Türkçe müzik ve unplugged performanslar"),
            ( 4, 0, "Müzik Yayını", "Akustik Türkçe müzik ve unplugged performanslar"),
            ( 6, 0, "Müzik Yayını", "Akustik Türkçe müzik ve unplugged performanslar"),
            ( 8, 0, "Müzik Yayını", "Akustik Türkçe müzik ve unplugged performanslar"),
            (10, 0, "Müzik Yayını", "Akustik Türkçe müzik ve unplugged performanslar"),
            (12, 0, "Müzik Yayını", "Akustik Türkçe müzik ve unplugged performanslar"),
            (14, 0, "Müzik Yayını", "Akustik Türkçe müzik ve unplugged performanslar"),
            (16, 0, "Müzik Yayını", "Akustik Türkçe müzik ve unplugged performanslar"),
            (18, 0, "Müzik Yayını", "Akustik Türkçe müzik ve unplugged performanslar"),
            (20, 0, "Müzik Yayını", "Akustik Türkçe müzik ve unplugged performanslar"),
            (22, 0, "Müzik Yayını", "Akustik Türkçe müzik ve unplugged performanslar"),
        ],
    },
    # ── POWERTURK EN İYİLER — 2 saatlik döngü ───────────────────
    "tr.powerturkeniyiler": {
        "tz": IST_TZ,
        "daily": [
            ( 0, 0, "Müzik Yayını", "En iyi Türkçe pop hitleri non-stop yayın"),
            ( 2, 0, "Müzik Yayını", "En iyi Türkçe pop hitleri non-stop yayın"),
            ( 4, 0, "Müzik Yayını", "En iyi Türkçe pop hitleri non-stop yayın"),
            ( 6, 0, "Müzik Yayını", "En iyi Türkçe pop hitleri non-stop yayın"),
            ( 8, 0, "Müzik Yayını", "En iyi Türkçe pop hitleri non-stop yayın"),
            (10, 0, "Müzik Yayını", "En iyi Türkçe pop hitleri non-stop yayın"),
            (12, 0, "Müzik Yayını", "En iyi Türkçe pop hitleri non-stop yayın"),
            (14, 0, "Müzik Yayını", "En iyi Türkçe pop hitleri non-stop yayın"),
            (16, 0, "Müzik Yayını", "En iyi Türkçe pop hitleri non-stop yayın"),
            (18, 0, "Müzik Yayını", "En iyi Türkçe pop hitleri non-stop yayın"),
            (20, 0, "Müzik Yayını", "En iyi Türkçe pop hitleri non-stop yayın"),
            (22, 0, "Müzik Yayını", "En iyi Türkçe pop hitleri non-stop yayın"),
        ],
    },
    # ── POWERTURK TAPTAZE — 2 saatlik yeni müzik döngüsü ────────
    "tr.powerturktaptaze": {
        "tz": IST_TZ,
        "daily": [
            ( 0, 0, "Müzik Yayını", "Güncel ve yeni Türkçe pop müzik yayını"),
            ( 2, 0, "Müzik Yayını", "Güncel ve yeni Türkçe pop müzik yayını"),
            ( 4, 0, "Müzik Yayını", "Güncel ve yeni Türkçe pop müzik yayını"),
            ( 6, 0, "Müzik Yayını", "Güncel ve yeni Türkçe pop müzik yayını"),
            ( 8, 0, "Müzik Yayını", "Güncel ve yeni Türkçe pop müzik yayını"),
            (10, 0, "Müzik Yayını", "Güncel ve yeni Türkçe pop müzik yayını"),
            (12, 0, "Müzik Yayını", "Güncel ve yeni Türkçe pop müzik yayını"),
            (14, 0, "Müzik Yayını", "Güncel ve yeni Türkçe pop müzik yayını"),
            (16, 0, "Müzik Yayını", "Güncel ve yeni Türkçe pop müzik yayını"),
            (18, 0, "Müzik Yayını", "Güncel ve yeni Türkçe pop müzik yayını"),
            (20, 0, "Müzik Yayını", "Güncel ve yeni Türkçe pop müzik yayını"),
            (22, 0, "Müzik Yayını", "Güncel ve yeni Türkçe pop müzik yayını"),
        ],
    },
    # ── POWER PLUS — 2 saatlik uluslararası pop döngüsü ─────────
    "tr.powerplus": {
        "tz": IST_TZ,
        "daily": [
            ( 0, 0, "Müzik Yayını", "Uluslararası pop hitleri ve İngilizce müzik yayını"),
            ( 2, 0, "Müzik Yayını", "Uluslararası pop hitleri ve İngilizce müzik yayını"),
            ( 4, 0, "Müzik Yayını", "Uluslararası pop hitleri ve İngilizce müzik yayını"),
            ( 6, 0, "Müzik Yayını", "Uluslararası pop hitleri ve İngilizce müzik yayını"),
            ( 8, 0, "Müzik Yayını", "Uluslararası pop hitleri ve İngilizce müzik yayını"),
            (10, 0, "Müzik Yayını", "Uluslararası pop hitleri ve İngilizce müzik yayını"),
            (12, 0, "Müzik Yayını", "Uluslararası pop hitleri ve İngilizce müzik yayını"),
            (14, 0, "Müzik Yayını", "Uluslararası pop hitleri ve İngilizce müzik yayını"),
            (16, 0, "Müzik Yayını", "Uluslararası pop hitleri ve İngilizce müzik yayını"),
            (18, 0, "Müzik Yayını", "Uluslararası pop hitleri ve İngilizce müzik yayını"),
            (20, 0, "Müzik Yayını", "Uluslararası pop hitleri ve İngilizce müzik yayını"),
            (22, 0, "Müzik Yayını", "Uluslararası pop hitleri ve İngilizce müzik yayını"),
        ],
    },

    # ── SLOW KARADENİZ — 2 saatlik döngü ────────────────────────
    "tr.slowkaradeniz": {
        "tz": IST_TZ,
        "daily": [(h, 0, "Karadeniz Yöresi Şarkıları", "Karadeniz yöresi türküleri ve horon müziği yayını") for h in range(0, 24, 2)],
    },

    # ── MÜZİK KANALLARI — 2 saatlik döngüler ─────────────────────
    "tr.toppop": {
        "tz": IST_TZ,
        "daily": [(h, 0, "Müzik Yayını", "Pop müzik video yayını") for h in range(0, 24, 2)],
    },
    "tr.finest": {
        "tz": IST_TZ,
        "daily": [(h, 0, "Türkçe Pop Yayını", "Türkçe pop müzik video yayını") for h in range(0, 24, 2)],
    },
    "tr.guclutv": {
        "tz": IST_TZ,
        "daily": [(h, 0, "Özgün Müzik Yayını", "Özgün ve yöresel Türk müziği yayını") for h in range(0, 24, 2)],
    },
    "tr.dostmuzik": {
        "tz": IST_TZ,
        "daily": [(h, 0, "Halk Müziği Yayını", "Türk halk müziği ve türkü yayını") for h in range(0, 24, 2)],
    },
    "tr.gencsms": {
        "tz": IST_TZ,
        "daily": [(h, 0, "Müzik Yayını", "Genç dinleyicilere yönelik müzik video yayını") for h in range(0, 24, 2)],
    },
    "tr.armatv": {
        "tz": IST_TZ,
        "daily": [(h, 0, "Arabesk Müzik Yayını", "Arabesk ve Türk sanat müziği video yayını") for h in range(0, 24, 2)],
    },
    "tr.silatv": {
        "tz": IST_TZ,
        "daily": [(h, 0, "Arabesk Müzik Yayını", "Arabesk ve duygusal Türk müziği yayını") for h in range(0, 24, 2)],
    },
    "tr.damartv": {
        "tz": IST_TZ,
        "daily": [(h, 0, "Damar Arabesk Yayını", "Damar arabesk müzik video yayını") for h in range(0, 24, 2)],
    },
    "tr.ezotv": {
        "tz": IST_TZ,
        "daily": [(h, 0, "Halk Müziği Yayını", "Türk halk müziği ve yöresel türküler yayını") for h in range(0, 24, 2)],
    },
    "tr.ezgitv": {
        "tz": IST_TZ,
        "daily": [(h, 0, "Özgün Müzik Yayını", "Özgün ve kültürel Türk müziği yayını") for h in range(0, 24, 2)],
    },

    # ── CHILL TV — 2 saatlik sakinleştirici müzik döngüsü ────────
    "tr.chilltv": {
        "tz": IST_TZ,
        "daily": [
            ( 0, 0, "Lounge Müzik Yayını", "Sakinleştirici, lounge ve ambient müzik yayını"),
            ( 2, 0, "Lounge Müzik Yayını", "Sakinleştirici, lounge ve ambient müzik yayını"),
            ( 4, 0, "Lounge Müzik Yayını", "Sakinleştirici, lounge ve ambient müzik yayını"),
            ( 6, 0, "Lounge Müzik Yayını", "Sakinleştirici, lounge ve ambient müzik yayını"),
            ( 8, 0, "Lounge Müzik Yayını", "Sakinleştirici, lounge ve ambient müzik yayını"),
            (10, 0, "Lounge Müzik Yayını", "Sakinleştirici, lounge ve ambient müzik yayını"),
            (12, 0, "Lounge Müzik Yayını", "Sakinleştirici, lounge ve ambient müzik yayını"),
            (14, 0, "Lounge Müzik Yayını", "Sakinleştirici, lounge ve ambient müzik yayını"),
            (16, 0, "Lounge Müzik Yayını", "Sakinleştirici, lounge ve ambient müzik yayını"),
            (18, 0, "Lounge Müzik Yayını", "Sakinleştirici, lounge ve ambient müzik yayını"),
            (20, 0, "Lounge Müzik Yayını", "Sakinleştirici, lounge ve ambient müzik yayını"),
            (22, 0, "Lounge Müzik Yayını", "Sakinleştirici, lounge ve ambient müzik yayını"),
        ],
    },

    # ── TEMPO TV ──────────────────────────────────────────────────
    "tr.tempotv": {
        "tz": IST_TZ,
        "daily": [
            ( 0, 0, "Klip Saati",    "Türkçe pop ve arabesk müzik klipleri"),
            ( 2, 0, "Klip Saati",    "Türkçe pop ve arabesk müzik klipleri"),
            ( 4, 0, "Klip Saati",    "Türkçe pop ve arabesk müzik klipleri"),
            ( 6, 0, "Klip Saati",    "Türkçe pop ve arabesk müzik klipleri"),
            ( 8, 0, "Klip Saati",    "Türkçe pop ve arabesk müzik klipleri"),
            (10, 0, "Klip Saati",    "Türkçe pop ve arabesk müzik klipleri"),
            (12, 0, "Klip Saati",    "Türkçe pop ve arabesk müzik klipleri"),
            (14, 0, "Klip Saati",    "Türkçe pop ve arabesk müzik klipleri"),
            (16, 0, "Klip Saati",    "Türkçe pop ve arabesk müzik klipleri"),
            (19, 0, "Müzik Programı","Canlı müzik yayını ve müzik programları"),
            (21, 0, "Müzik Programı","Canlı müzik yayını ve müzik programları"),
            (23, 0, "Müzik Programı","Canlı müzik yayını ve müzik programları"),
        ],
    },

    # ── KRAL TV KANALLARI ─────────────────────────────────────────
    "tr.kraltv": {
        "tz": IST_TZ,
        "daily": [
            ( 0, 0, "Kral TV Yayını", "Türkü, halk müziği ve Türk sanat müziği video yayını"),
            ( 2, 0, "Kral TV Yayını", "Türkü, halk müziği ve Türk sanat müziği video yayını"),
            ( 4, 0, "Kral TV Yayını", "Türkü, halk müziği ve Türk sanat müziği video yayını"),
            ( 6, 0, "Kral TV Yayını", "Türkü, halk müziği ve Türk sanat müziği video yayını"),
            ( 8, 0, "Kral TV Yayını", "Türkü, halk müziği ve Türk sanat müziği video yayını"),
            (10, 0, "Kral TV Yayını", "Türkü, halk müziği ve Türk sanat müziği video yayını"),
            (12, 0, "Kral TV Yayını", "Türkü, halk müziği ve Türk sanat müziği video yayını"),
            (14, 0, "Kral TV Yayını", "Türkü, halk müziği ve Türk sanat müziği video yayını"),
            (16, 0, "Kral TV Yayını", "Türkü, halk müziği ve Türk sanat müziği video yayını"),
            (18, 0, "Kral TV Yayını", "Türkü, halk müziği ve Türk sanat müziği video yayını"),
            (20, 0, "Kral TV Yayını", "Türkü, halk müziği ve Türk sanat müziği video yayını"),
            (22, 0, "Kral TV Yayını", "Türkü, halk müziği ve Türk sanat müziği video yayını"),
        ],
    },
    "tr.kralpoptv": {
        "tz": IST_TZ,
        "daily": [
            ( 0, 0, "Kral Pop TV Yayını", "Türkçe pop müzik video kanalı yayını"),
            ( 2, 0, "Kral Pop TV Yayını", "Türkçe pop müzik video kanalı yayını"),
            ( 4, 0, "Kral Pop TV Yayını", "Türkçe pop müzik video kanalı yayını"),
            ( 6, 0, "Kral Pop TV Yayını", "Türkçe pop müzik video kanalı yayını"),
            ( 8, 0, "Kral Pop TV Yayını", "Türkçe pop müzik video kanalı yayını"),
            (10, 0, "Kral Pop TV Yayını", "Türkçe pop müzik video kanalı yayını"),
            (12, 0, "Kral Pop TV Yayını", "Türkçe pop müzik video kanalı yayını"),
            (14, 0, "Kral Pop TV Yayını", "Türkçe pop müzik video kanalı yayını"),
            (16, 0, "Kral Pop TV Yayını", "Türkçe pop müzik video kanalı yayını"),
            (18, 0, "Kral Pop TV Yayını", "Türkçe pop müzik video kanalı yayını"),
            (20, 0, "Kral Pop TV Yayını", "Türkçe pop müzik video kanalı yayını"),
            (22, 0, "Kral Pop TV Yayını", "Türkçe pop müzik video kanalı yayını"),
        ],
    },

    # ── NR1 / NUMBER1 KANALLARI ──────────────────────────────────
    "tr.nr1rap": {
        "tz": IST_TZ,
        "daily": [
            ( 0, 0, "NR1 Rap Yayını", "Türkçe rap, hip-hop ve trap müzik yayını"),
            ( 2, 0, "NR1 Rap Yayını", "Türkçe rap, hip-hop ve trap müzik yayını"),
            ( 4, 0, "NR1 Rap Yayını", "Türkçe rap, hip-hop ve trap müzik yayını"),
            ( 6, 0, "NR1 Rap Yayını", "Türkçe rap, hip-hop ve trap müzik yayını"),
            ( 8, 0, "NR1 Rap Yayını", "Türkçe rap, hip-hop ve trap müzik yayını"),
            (10, 0, "NR1 Rap Yayını", "Türkçe rap, hip-hop ve trap müzik yayını"),
            (12, 0, "NR1 Rap Yayını", "Türkçe rap, hip-hop ve trap müzik yayını"),
            (14, 0, "NR1 Rap Yayını", "Türkçe rap, hip-hop ve trap müzik yayını"),
            (16, 0, "NR1 Rap Yayını", "Türkçe rap, hip-hop ve trap müzik yayını"),
            (18, 0, "NR1 Rap Yayını", "Türkçe rap, hip-hop ve trap müzik yayını"),
            (20, 0, "NR1 Rap Yayını", "Türkçe rap, hip-hop ve trap müzik yayını"),
            (22, 0, "NR1 Rap Yayını", "Türkçe rap, hip-hop ve trap müzik yayını"),
        ],
    },
    "tr.number1tv": {
        "tz": IST_TZ,
        "daily": [
            ( 0, 0, "Müzik Yayını", "Yabancı pop müzik video yayını"),
            ( 2, 0, "Müzik Yayını", "Yabancı pop müzik video yayını"),
            ( 4, 0, "Müzik Yayını", "Yabancı pop müzik video yayını"),
            ( 6, 0, "Müzik Yayını", "Yabancı pop müzik video yayını"),
            ( 8, 0, "Müzik Yayını", "Yabancı pop müzik video yayını"),
            (10, 0, "Müzik Yayını", "Yabancı pop müzik video yayını"),
            (12, 0, "Müzik Yayını", "Yabancı pop müzik video yayını"),
            (14, 0, "Müzik Yayını", "Yabancı pop müzik video yayını"),
            (16, 0, "Müzik Yayını", "Yabancı pop müzik video yayını"),
            (18, 0, "Müzik Yayını", "Yabancı pop müzik video yayını"),
            (20, 0, "Müzik Yayını", "Yabancı pop müzik video yayını"),
            (22, 0, "Müzik Yayını", "Yabancı pop müzik video yayını"),
        ],
    },
    "tr.number1turk": {
        "tz": IST_TZ,
        "daily": [
            ( 0, 0, "Number1 Türk Yayını", "Türkçe pop ve arabesk müzik video yayını"),
            ( 2, 0, "Number1 Türk Yayını", "Türkçe pop ve arabesk müzik video yayını"),
            ( 4, 0, "Number1 Türk Yayını", "Türkçe pop ve arabesk müzik video yayını"),
            ( 6, 0, "Number1 Türk Yayını", "Türkçe pop ve arabesk müzik video yayını"),
            ( 8, 0, "Number1 Türk Yayını", "Türkçe pop ve arabesk müzik video yayını"),
            (10, 0, "Number1 Türk Yayını", "Türkçe pop ve arabesk müzik video yayını"),
            (12, 0, "Number1 Türk Yayını", "Türkçe pop ve arabesk müzik video yayını"),
            (14, 0, "Number1 Türk Yayını", "Türkçe pop ve arabesk müzik video yayını"),
            (16, 0, "Number1 Türk Yayını", "Türkçe pop ve arabesk müzik video yayını"),
            (18, 0, "Number1 Türk Yayını", "Türkçe pop ve arabesk müzik video yayını"),
            (20, 0, "Number1 Türk Yayını", "Türkçe pop ve arabesk müzik video yayını"),
            (22, 0, "Number1 Türk Yayını", "Türkçe pop ve arabesk müzik video yayını"),
        ],
    },
    "tr.nr1ask": {
        "tz": IST_TZ,
        "daily": [
            ( 0, 0, "Romantik Türkçe Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik video yayını"),
            ( 2, 0, "Romantik Türkçe Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik video yayını"),
            ( 4, 0, "Romantik Türkçe Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik video yayını"),
            ( 6, 0, "Romantik Türkçe Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik video yayını"),
            ( 8, 0, "Romantik Türkçe Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik video yayını"),
            (10, 0, "Romantik Türkçe Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik video yayını"),
            (12, 0, "Romantik Türkçe Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik video yayını"),
            (14, 0, "Romantik Türkçe Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik video yayını"),
            (16, 0, "Romantik Türkçe Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik video yayını"),
            (18, 0, "Romantik Türkçe Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik video yayını"),
            (20, 0, "Romantik Türkçe Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik video yayını"),
            (22, 0, "Romantik Türkçe Müzik Yayını", "Aşk şarkıları ve romantik Türkçe müzik video yayını"),
        ],
    },
    "tr.nr1dance": {
        "tz": IST_TZ,
        "daily": [
            ( 0, 0, "NR1 Dance Yayını", "Dance, elektronik ve club müzik video yayını"),
            ( 2, 0, "NR1 Dance Yayını", "Dance, elektronik ve club müzik video yayını"),
            ( 4, 0, "NR1 Dance Yayını", "Dance, elektronik ve club müzik video yayını"),
            ( 6, 0, "NR1 Dance Yayını", "Dance, elektronik ve club müzik video yayını"),
            ( 8, 0, "NR1 Dance Yayını", "Dance, elektronik ve club müzik video yayını"),
            (10, 0, "NR1 Dance Yayını", "Dance, elektronik ve club müzik video yayını"),
            (12, 0, "NR1 Dance Yayını", "Dance, elektronik ve club müzik video yayını"),
            (14, 0, "NR1 Dance Yayını", "Dance, elektronik ve club müzik video yayını"),
            (16, 0, "NR1 Dance Yayını", "Dance, elektronik ve club müzik video yayını"),
            (18, 0, "NR1 Dance Yayını", "Dance, elektronik ve club müzik video yayını"),
            (20, 0, "NR1 Dance Yayını", "Dance, elektronik ve club müzik video yayını"),
            (22, 0, "NR1 Dance Yayını", "Dance, elektronik ve club müzik video yayını"),
        ],
    },
    "tr.nr1damar": {
        "tz": IST_TZ,
        "daily": [
            ( 0, 0, "Rap Müzik Yayını", "Rap, hip-hop ve damar müzik video yayını"),
            ( 2, 0, "Rap Müzik Yayını", "Rap, hip-hop ve damar müzik video yayını"),
            ( 4, 0, "Rap Müzik Yayını", "Rap, hip-hop ve damar müzik video yayını"),
            ( 6, 0, "Rap Müzik Yayını", "Rap, hip-hop ve damar müzik video yayını"),
            ( 8, 0, "Rap Müzik Yayını", "Rap, hip-hop ve damar müzik video yayını"),
            (10, 0, "Rap Müzik Yayını", "Rap, hip-hop ve damar müzik video yayını"),
            (12, 0, "Rap Müzik Yayını", "Rap, hip-hop ve damar müzik video yayını"),
            (14, 0, "Rap Müzik Yayını", "Rap, hip-hop ve damar müzik video yayını"),
            (16, 0, "Rap Müzik Yayını", "Rap, hip-hop ve damar müzik video yayını"),
            (18, 0, "Rap Müzik Yayını", "Rap, hip-hop ve damar müzik video yayını"),
            (20, 0, "Rap Müzik Yayını", "Rap, hip-hop ve damar müzik video yayını"),
            (22, 0, "Rap Müzik Yayını", "Rap, hip-hop ve damar müzik video yayını"),
        ],
    },

    # ── MED MÜZİK TV — 2 saatlik döngü, 7/24 ────────────────────
    "tr.medmuziktv": {
        "tz": IST_TZ,
        "daily": [
            ( 0,  0, "Müzik Yayını", "Çeşitli sanatçılardan Kürtçe müzik yayını"),
            ( 2,  0, "Müzik Yayını", "Çeşitli sanatçılardan Kürtçe müzik yayını"),
            ( 4,  0, "Müzik Yayını", "Çeşitli sanatçılardan Kürtçe müzik yayını"),
            ( 6,  0, "Müzik Yayını", "Çeşitli sanatçılardan Kürtçe müzik yayını"),
            ( 8,  0, "Müzik Yayını", "Çeşitli sanatçılardan Kürtçe müzik yayını"),
            (10,  0, "Müzik Yayını", "Çeşitli sanatçılardan Kürtçe müzik yayını"),
            (12,  0, "Müzik Yayını", "Çeşitli sanatçılardan Kürtçe müzik yayını"),
            (14,  0, "Müzik Yayını", "Çeşitli sanatçılardan Kürtçe müzik yayını"),
            (16,  0, "Müzik Yayını", "Çeşitli sanatçılardan Kürtçe müzik yayını"),
            (18,  0, "Müzik Yayını", "Çeşitli sanatçılardan Kürtçe müzik yayını"),
            (20,  0, "Müzik Yayını", "Çeşitli sanatçılardan Kürtçe müzik yayını"),
            (22,  0, "Müzik Yayını", "Çeşitli sanatçılardan Kürtçe müzik yayını"),
        ],
    },

    # ── NEO HABER — her gün aynı, Türkiye saati ──────────────────
    "tr.neohabertv": {
        "tz": IST_TZ,
        "daily": [
            ( 8,  0, "Uyanma Servisi",        "Kutluhan Nesil ile"),
            (11,  0, "Ekonomi Ajansı",         "Hanzade Avcıoğlu ile"),
            (12,  0, "Gün Ortası",             "Senem Gökdağ ile"),
            (14,  0, "Aramızda Kalsın",        "Esra Kavrukkoca ile"),
            (15,  0, "Dokun Hayata",           "Elif Akar ile"),
            (17,  0, "Beyaz Masa",             "Ertuğrut Turan ile"),
            (18, 30, "Ana Haber",              "Alper Esin Baran ile"),
            (19, 30, "Neo Haber Akşam Kuşağı", "Neo Haber akşam yayını"),
            (23,  0, "Gece Kuşağı Yayını",    "Neo Haber gece yayını"),
        ],
    },

    # ── MCE TV — haftalık, Istanbul saati ────────────────────────
    "tr.mceutv": {
        "tz": IST_TZ,
        "days": {
            0: [  # PAZARTESİ
                ( 5,  0, "Hatim Saati"),
                ( 6,  0, "Dua Vakti"),
                ( 6, 30, "Efendimiz (s.a.v.)"),
                ( 7,  0, "Dini Programlar"),
                ( 7, 30, "Çocuk Kuşağı"),
                ( 8, 30, "Haber Yorum"),
                ( 9, 30, "Çınarın Gölgesinde"),
                (10, 15, "Aile ve Çocuk Eğitimi Kuşağı"),
                (11,  0, "Mavi Rüya"),
                (12,  0, "Haberler"),
                (14,  0, "Yemek Programı - Pasta Börek"),
                (15, 15, "İki Dünya Arasında"),
                (16, 15, "Gençlere Özel"),
                (16, 35, "Çocuk Kuşağı"),
                (17,  0, "Haber-Yorum"),
                (18,  0, "TV Filmi"),
                (19,  0, "Kültür-Eğitim"),
                (19, 30, "Haber-Yorum"),
                (21,  0, "Ana Haber"),
                (22,  0, "Ekip 1"),
                (23,  0, "Bamteli"),
                (23, 30, "Kutup Yıldızları"),
                ( 0,  0, "Gece Haberleri"),
                ( 2,  0, "Beşinci Boyut"),
                ( 3,  0, "Almanca + İngilizce"),
                ( 3, 45, "Ana Dizi Kuşağı"),
            ],
            1: [  # SALI
                ( 5,  0, "Hatim Saati"),
                ( 6,  0, "Dua Vakti"),
                ( 6, 30, "Efendimiz (s.a.v.)"),
                ( 7,  0, "Dini Programlar"),
                ( 7, 30, "Çocuk Kuşağı"),
                ( 8, 30, "Haber Yorum"),
                ( 9, 30, "Çınarın Gölgesinde"),
                (10, 15, "Aile ve Çocuk Eğitimi Kuşağı"),
                (11,  0, "Mavi Rüya"),
                (12,  0, "Haberler"),
                (14,  0, "Yemek Programı - Pasta Börek"),
                (15, 15, "İki Dünya Arasında"),
                (16, 15, "Gençlere Özel"),
                (16, 35, "Çocuk Kuşağı"),
                (17,  0, "Haber-Yorum"),
                (18,  0, "TV Filmi"),
                (19,  0, "Kültür-Eğitim"),
                (19, 30, "Haber-Yorum"),
                (21,  0, "Ana Haber"),
                (22,  0, "Kendi Okulumüza Doğru"),
                (23,  0, "Bamteli"),
                (23, 30, "Nurdan Hüzmeler"),
                ( 0,  0, "Gece Haberleri"),
                ( 2,  0, "Beşinci Boyut"),
                ( 3,  0, "Almanca + İngilizce"),
                ( 3, 45, "Ana Dizi Kuşağı"),
            ],
            2: [  # ÇARŞAMBA
                ( 5,  0, "Hatim Saati"),
                ( 6,  0, "Dua Vakti"),
                ( 6, 30, "Efendimiz (s.a.v.)"),
                ( 7,  0, "Dini Programlar"),
                ( 7, 30, "Çocuk Kuşağı"),
                ( 8, 30, "Haber Yorum"),
                ( 9, 30, "Çınarın Gölgesinde"),
                (10, 15, "Aile ve Çocuk Eğitimi Kuşağı"),
                (11,  0, "Mavi Rüya"),
                (12,  0, "Haberler"),
                (14,  0, "Yemek Programı - Pasta Börek"),
                (15, 15, "İki Dünya Arasında"),
                (16, 15, "Gençlere Özel"),
                (16, 35, "Çocuk Kuşağı"),
                (17,  0, "Haber-Yorum"),
                (18,  0, "TV Filmi"),
                (19,  0, "Kültür-Eğitim"),
                (19, 30, "Haber-Yorum"),
                (21,  0, "Ana Haber"),
                (22,  0, "Ve İnsan Aldandı"),
                (23,  0, "Bamteli"),
                (23, 30, "Etik Politik"),
                ( 0,  0, "Gece Haberleri"),
                ( 2,  0, "Beşinci Boyut"),
                ( 3,  0, "Almanca + İngilizce"),
                ( 3, 45, "Ana Dizi Kuşağı"),
            ],
            3: [  # PERŞEMBE
                ( 5,  0, "Hatim Saati"),
                ( 6,  0, "Dua Vakti"),
                ( 6, 30, "Efendimiz (s.a.v.)"),
                ( 7,  0, "Dini Programlar"),
                ( 7, 30, "Çocuk Kuşağı"),
                ( 8, 30, "Haber Yorum"),
                ( 9, 30, "Çınarın Gölgesinde"),
                (10, 15, "Aile ve Çocuk Eğitimi Kuşağı"),
                (11,  0, "Mavi Rüya"),
                (12,  0, "Haberler"),
                (14,  0, "Yemek Programı - Pasta Börek"),
                (15, 15, "İki Dünya Arasında"),
                (16, 15, "Gençlere Özel"),
                (16, 35, "Çocuk Kuşağı"),
                (17,  0, "Haber-Yorum"),
                (18,  0, "TV Filmi"),
                (19,  0, "Kültür-Eğitim"),
                (19, 30, "Haber-Yorum"),
                (21,  0, "Ana Haber"),
                (22,  0, "Büyük Buluşma"),
                (23,  0, "Bamteli"),
                (23, 30, "Dini Aktüel"),
                ( 0,  0, "Gece Haberleri"),
                ( 2,  0, "Beşinci Boyut"),
                ( 3,  0, "Almanca + İngilizce"),
                ( 3, 45, "Ana Dizi Kuşağı"),
            ],
            4: [  # CUMA
                ( 5,  0, "Hatim Saati"),
                ( 6,  0, "Dua Vakti"),
                ( 6, 30, "Efendimiz (s.a.v.)"),
                ( 7,  0, "Dini Programlar"),
                ( 7, 30, "Çocuk Kuşağı"),
                ( 8, 30, "Haber Yorum"),
                ( 9, 30, "Çınarın Gölgesinde"),
                (10, 15, "Aile ve Çocuk Eğitimi Kuşağı"),
                (11,  0, "Mavi Rüya"),
                (12,  0, "Haberler"),
                (14,  0, "Yemek Programı - Pasta Börek"),
                (15, 15, "İki Dünya Arasında"),
                (16, 15, "Gençlere Özel"),
                (16, 35, "Çocuk Kuşağı"),
                (17,  0, "Haber-Yorum"),
                (18,  0, "TV Filmi"),
                (19,  0, "Kültür-Eğitim"),
                (19, 30, "Haber-Yorum"),
                (21,  0, "Ana Haber"),
                (22,  0, "Güz Gülleri"),
                (23,  0, "Bamteli"),
                (23, 30, "Nurdan Hüzmeler"),
                ( 0,  0, "Gece Haberleri"),
                ( 2,  0, "Beşinci Boyut"),
                ( 3,  0, "Almanca + İngilizce"),
                ( 3, 45, "Ana Dizi Kuşağı"),
            ],
            5: [  # CUMARTESİ
                ( 5,  0, "Hatim Saati"),
                ( 6,  0, "Dua Vakti"),
                ( 6, 30, "Efendimiz (s.a.v.)"),
                ( 7,  0, "Dini Programlar"),
                ( 7, 30, "Çocuk Kuşağı"),
                ( 8, 30, "Haber Yorum"),
                ( 9, 30, "Çınarın Gölgesinde"),
                (10, 15, "Aile ve Çocuk Eğitimi Kuşağı"),
                (11,  0, "Mavi Rüya"),
                (12,  0, "Haberler"),
                (14,  0, "Yemek Programı - Yeşil Elma"),
                (15, 15, "İki Dünya Arasında"),
                (16, 15, "Gençlere Özel"),
                (16, 35, "Çocuk Kuşağı"),
                (17,  0, "Haber-Yorum"),
                (18,  0, "TV Filmi"),
                (19,  0, "Kültür-Eğitim"),
                (19, 30, "Haber-Yorum"),
                (21,  0, "Ana Haber"),
                (22,  0, "Küçük Gelin"),
                (23,  0, "Bamteli"),
                (23, 30, "Kitabın Ortası"),
                ( 0,  0, "Gece Haberleri"),
                ( 2,  0, "Beşinci Boyut"),
                ( 3,  0, "Almanca + İngilizce"),
                ( 3, 45, "Ana Dizi Kuşağı"),
            ],
            6: [  # PAZAR
                ( 5,  0, "Hatim Saati"),
                ( 6,  0, "Dua Vakti"),
                ( 6, 30, "Efendimiz (s.a.v.)"),
                ( 7,  0, "Dini Programlar"),
                ( 7, 30, "Çocuk Kuşağı"),
                ( 8, 30, "Haber Yorum"),
                ( 9, 30, "Çınarın Gölgesinde"),
                (10, 15, "Aile ve Çocuk Eğitimi Kuşağı"),
                (11,  0, "Mavi Rüya"),
                (12,  0, "Haberler"),
                (14,  0, "Yemek Programı - Yeşil Elma"),
                (15, 15, "İki Dünya Arasında"),
                (16, 15, "Gençlere Özel"),
                (16, 35, "Çocuk Kuşağı"),
                (17,  0, "Haber-Yorum"),
                (18,  0, "TV Filmi"),
                (19,  0, "Kültür-Eğitim"),
                (19, 30, "Haber-Yorum"),
                (21,  0, "Ana Haber"),
                (22,  0, "Ritmini Arayan Kalpler"),
                (23,  0, "Bamteli"),
                (23, 30, "Dünyalem"),
                ( 0,  0, "Gece Haberleri"),
                ( 2,  0, "Beşinci Boyut"),
                ( 3,  0, "Almanca + İngilizce"),
                ( 3, 45, "Ana Dizi Kuşağı"),
            ],
        },
    },

    # ── KANAL AVRUPA — haftalık, Almanya saati ───────────────────
    "tr.kanalavrupatv": {
        "tz": DE_TZ,
        "days": {
        0: [  # PAZARTESİ
            ( 6,  0, "Klip Saati"),
            ( 6, 45, "Yaşayan Tarih"),
            ( 7, 30, "Anahaber"),
            ( 8, 45, "Bakış Açısı"),
            (10,  0, "Ege Gündemİ"),
            (11, 45, "Estetik ve Sağlık"),
            (13,  0, "Anahaber"),
            (13, 45, "Türk Dünyası"),
            (15,  0, "Kadınca"),
            (16, 45, "Avrupa Klip Magazin"),
            (17, 30, "Anahaber"),
            (18, 15, "Bildung & Beruf"),
            (19, 45, "100 Yıllık Türküler"),
            (21,  0, "Anahaber"),
            (22, 15, "Spor Avrupa"),
            (23, 30, "Anahaber"),
            ( 0, 30, "Bakış Açısı"),
            ( 2, 15, "Bizsiz Olmaz 1"),
            ( 3, 45, "Namekan Türküler"),
            ( 5,  0, "Türkülerimiz"),
        ],
        1: [  # SALI
            ( 6,  0, "Klip Saati"),
            ( 6, 45, "Belgesel"),
            ( 7, 30, "Anahaber"),
            ( 8, 45, "Sivil İnsiyatif"),
            (10,  0, "Berlin Gündemi"),
            (11, 45, "Spor Avrupa"),
            (13,  0, "Anahaber"),
            (13, 45, "Türk Dünyası"),
            (15,  0, "100 Yıllık Türküler"),
            (16, 45, "Avrupa Klip Magazin"),
            (17, 30, "Anahaber"),
            (18, 15, "Sağlık Saati"),
            (19, 45, "Karadeniz Show"),
            (21,  0, "Anahaber"),
            (22, 15, "Ersoy Show"),
            (23, 30, "Anahaber"),
            ( 0, 30, "Sivil İnsiyatif"),
            ( 2, 15, "Bizsiz Olmaz 2"),
            ( 3, 45, "Asrın Türküleri"),
            ( 5,  0, "Türkülerimiz"),
        ],
        2: [  # ÇARŞAMBA
            ( 6,  0, "Klip Saati"),
            ( 7, 30, "Anahaber"),
            ( 8, 45, "Avrupa Baskısı"),
            (10,  0, "Sağlıklı Yaşamın Sırları"),
            (11, 45, "Karadeniz Show"),
            (13,  0, "Anahaber"),
            (13, 45, "Türk Dünyası"),
            (15,  0, "Ersoy Show"),
            (16, 45, "Avrupa Klip Magazin"),
            (17, 30, "Anahaber"),
            (18, 15, "Rota"),
            (19, 45, "Her Türkü Bir Hikaye"),
            (21,  0, "Anahaber"),
            (22, 15, "İş Dünyası"),
            (23, 30, "Anahaber"),
            ( 0, 30, "Avrupa Baskısı"),
            ( 2, 15, "Avrupalı Türkler"),
            ( 3, 45, "Yolcu Türküsü"),
            ( 5,  0, "Türkülerimiz"),
        ],
        3: [  # PERŞEMBE
            ( 6,  0, "Klip Saati"),
            ( 7, 30, "Anahaber"),
            ( 8, 45, "Avrupa Arenası"),
            (10,  0, "Rota"),
            (11, 45, "Suskun Türküler"),
            (13,  0, "Anahaber"),
            (13, 45, "Türk Dünyası"),
            (15,  0, "İş Dünyası"),
            (16, 45, "Avrupa Klip Magazin"),
            (17, 30, "Anahaber"),
            (18, 15, "Sağlıklı Yaşamın Sırları"),
            (19, 45, "Anadolu Diyarı"),
            (21,  0, "Anahaber"),
            (22, 15, "Rahmet Vakti"),
            (23, 30, "Anahaber"),
            ( 0, 30, "Avrupa Arenası"),
            ( 2, 15, "Bizsiz Olmaz 1"),
            ( 3, 45, "Ay Dost"),
            ( 5,  0, "Türkülerimiz"),
        ],
        4: [  # CUMA
            ( 6,  0, "Klip Saati"),
            ( 7, 30, "Anahaber"),
            ( 8, 45, "Ateş Çemberi"),
            (10,  0, "Sağlıklı Yaşamın Sırları"),
            (11, 45, "Anadolu Diyarı"),
            (13,  0, "Anahaber"),
            (13, 45, "Türk Dünyası"),
            (15,  0, "Rahmet Vakti"),
            (16, 45, "Avrupa Klip Magazin"),
            (17, 30, "Anahaber"),
            (18, 15, "Ege Gündemi"),
            (19, 45, "Anadolu Rock"),
            (21,  0, "Anahaber"),
            (22, 15, "Hukuk Masası"),
            (23, 30, "Anahaber"),
            ( 0, 30, "Ateş Çemberi"),
            ( 2, 15, "Bizsiz Olmaz 2"),
            ( 3, 45, "Şarkılardan Fal Tutum"),
            ( 5,  0, "Türkülerimiz"),
        ],
        5: [  # CUMARTESİ
            ( 6,  0, "Klip Saati"),
            ( 6, 30, "Bizsiz Olmaz 1"),
            ( 6, 45, "Bizsiz Olmaz 1"),
            ( 7, 30, "Anahaber"),
            ( 8, 30, "İş Dünyası"),
            ( 9, 45, "Avrupa Masası"),
            (10,  0, "Yaşayan Tarih"),
            (10, 15, "Emin Adımlar"),
            (11, 45, "Hukuk Masası"),
            (13,  0, "Sağlık Saati"),
            (13, 30, "Kadınca"),
            (14, 45, "Brüksel Gündemi"),
            (15, 15, "Sağlıklı Yaşamın Sırları"),
            (16, 30, "Türk Dünyası"),
            (16, 45, "Sivil İnsiyatif"),
            (17, 45, "Suskun Türküler"),
            (18, 15, "Berlin Gündemi"),
            (19, 45, "Bakış Açısı"),
            (21,  0, "Anahaber"),
            (22, 15, "Avrupa Baskısı"),
            (23, 30, "Anahaber"),
            ( 0, 30, "Asrın Türküleri"),
            ( 2, 15, "Avrupalı Türkler"),
            ( 2, 30, "Bizsiz Olmaz 1"),
            ( 3, 45, "Tümence"),
            ( 5,  0, "Türkülerimiz"),
        ],
        6: [  # PAZAR
            ( 6,  0, "Klip Saati"),
            ( 6, 30, "Bizsiz Olmaz 2"),
            ( 6, 45, "Bizsiz Olmaz 2"),
            ( 7, 30, "Anahaber"),
            ( 8, 45, "Avrupa Masası"),
            (10, 15, "Emin Adımlar"),
            (11, 45, "Estetik ve Sağlık"),
            (13, 30, "Kadınca"),
            (15, 15, "Sağlıklı Yaşamın Sırları"),
            (16, 30, "Türk Dünyası"),
            (17, 45, "Suskun Türküler"),
            (19, 45, "Avrupa Arenası"),
            (21,  0, "Anahaber"),
            (21, 45, "Ateş Çemberi"),
            (23,  0, "Ekmek Teknesi"),
            (23, 30, "Anahaber"),
            ( 0, 45, "Asrın Türküleri"),
            ( 2, 30, "Bizsiz Olmaz 1"),
            ( 3, 45, "Bir Demet Türkü"),
            ( 5,  0, "Türkülerimiz"),
        ],
        },
    },
}


class StaticScheduleAdapter(BaseAdapter):
    prefix = "staticschedule"

    def fetch(self, source_id: str, channel_id: str) -> List[Programme]:
        schedule = SCHEDULES.get(source_id)
        if not schedule:
            return []
        return self._generate(schedule, channel_id)

    def _generate(self, schedule: dict, channel_id: str) -> List[Programme]:
        now = ist(datetime.now())
        out: List[Programme] = []
        sched_tz = schedule.get("tz", DE_TZ)

        now_local = now.astimezone(sched_tz)
        monday = (now_local - timedelta(days=now_local.weekday())).replace(
            hour=0, minute=0, second=0, microsecond=0)

        if "daily" in schedule:
            # Günlük döngü: her gün aynı, 4 hafta üret
            programs = schedule["daily"]
            for day_offset in range(-7, 22):
                day_base = monday + timedelta(days=day_offset)
                self._add_programs(programs, day_base, sched_tz, channel_id, out)
        else:
            # Haftalık döngü
            days = schedule.get("days", {})
            for week_offset in range(-1, 3):
                week_start = monday + timedelta(weeks=week_offset)
                for weekday, programs in days.items():
                    day_base = week_start + timedelta(days=weekday)
                    self._add_programs(programs, day_base, sched_tz, channel_id, out)

        return out

    def _add_programs(self, programs, day_base, sched_tz, channel_id, out):
        for entry in programs:
            h, m, title = entry[0], entry[1], entry[2]
            desc = entry[3] if len(entry) > 3 else None
            day = day_base + timedelta(days=1) if h < 6 else day_base
            start_dt = datetime(day.year, day.month, day.day, h, m,
                                tzinfo=sched_tz).astimezone(IST_TZ)
            out.append(Programme(
                channel_id=channel_id,
                start=start_dt,
                title=title,
                desc=desc,
                source=self.prefix,
            ))
